import pluginJs from '@eslint/js';
import globalVariables from 'globals';
import pluginTs, { ConfigWithExtends } from 'typescript-eslint';

// see https://eslint.org/docs/latest/rules/
export const jsStrict = pluginTs.config(
  pluginJs.configs.recommended,
  // https://eslint.org/docs/latest/rules/#possible-problems
  {
    rules: {
      'array-callback-return': 'off',
      'no-await-in-loop': 'off',
      'no-constructor-return': 'off',
      'no-duplicate-imports': 'off',
      'no-inner-declarations': 'off',
      'no-promise-executor-return': 'off',
      'no-self-compare': 'off',
      'no-template-curly-in-string': 'off',
      'no-unmodified-loop-condition': 'off',
      'no-unreachable-loop': 'off',
      'no-use-before-define': 'off',
      'no-useless-assignment': 'off',
      'require-atomic-updates': 'off',
    },
  },
  // https://eslint.org/docs/latest/rules/#suggestions
  {
    rules: {
      'accessor-pairs': 'off',
      'arrow-body-style': 'off',
      'block-scoped-var': 'off',
      camelcase: 'off',
      'capitalized-comments': 'off',
      'class-methods-use-this': 'off',
      complexity: 'off',
      'consistent-return': 'off',
      'consistent-this': 'off',
      curly: 'off',
      'default-case': 'off',
      'default-case-last': 'off',
      'default-param-last': 'off',
      'dot-notation': 'off',
      eqeqeq: 'off',
      'func-name-matching': 'off',
      'func-names': 'off',
      'func-style': 'off',
      'grouped-accessor-pairs': 'off',
      'guard-for-in': 'off',
      'id-denylist': 'off',
      'id-length': 'off',
      'id-match': 'off',
      'init-declarations': 'off',
      'logical-assignment-operators': 'off',
      'max-classes-per-file': 'off',
      'max-depth': 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-nested-callbacks': 'off',
      'max-params': 'off',
      'max-statements': 'off',
      'new-cap': 'off',
      'no-alert': 'off',
      'no-array-constructor': 'off',
      'no-bitwise': 'off',
      'no-caller': 'off',
      'no-console': 'off',
      'no-continue': 'off',
      'no-div-regex': 'off',
      'no-else-return': 'off',
      'no-empty-function': 'off',
      'no-eq-null': 'off',
      'no-eval': 'off',
      'no-extend-native': 'off',
      'no-extra-bind': 'off',
      'no-extra-label': 'off',
      'no-implicit-coercion': 'off',
      'no-implicit-globals': 'off',
      'no-implied-eval': 'off',
      'no-inline-comments': 'off',
      'no-invalid-this': 'off',
      'no-iterator': 'off',
      'no-label-var': 'off',
      'no-labels': 'off',
      'no-lone-blocks': 'off',
      'no-lonely-if': 'off',
      'no-loop-func': 'off',
      'no-magic-numbers': 'off',
      'no-multi-assign': 'off',
      'no-multi-str': 'off',
      'no-negated-condition': 'off',
      'no-nested-ternary': 'off',
      'no-new': 'off',
      'no-new-func': 'off',
      'no-new-wrappers': 'off',
      'no-object-constructor': 'off',
      'no-octal-escape': 'off',
      'no-param-reassign': 'off',
      'no-plusplus': 'off',
      'no-proto': 'off',
      'no-restricted-exports': 'off',
      'no-restricted-globals': 'off',
      'no-restricted-imports': 'off',
      'no-restricted-properties': 'off',
      'no-restricted-syntax': 'off',
      'no-return-assign': 'off',
      'no-script-url': 'off',
      'no-sequences': 'off',
      'no-shadow': 'off',
      'no-ternary': 'off',
      'no-throw-literal': 'off',
      'no-undef-init': 'off',
      'no-undefined': 'off',
      'no-underscore-dangle': 'off',
      'no-unneeded-ternary': 'off',
      'no-unused-expressions': 'off',
      'no-useless-call': 'off',
      'no-useless-computed-key': 'off',
      'no-useless-concat': 'off',
      'no-useless-constructor': 'off',
      'no-useless-rename': 'off',
      'no-useless-return': 'off',
      'no-var': 'off',
      'no-void': 'off',
      'no-warning-comments': 'off',
      'object-shorthand': 'off',
      'one-var': 'off',
      'operator-assignment': 'off',
      'prefer-arrow-callback': 'off',
      'prefer-const': 'off',
      'prefer-destructuring': 'off',
      'prefer-exponentiation-operator': 'off',
      'prefer-named-capture-group': 'off',
      'prefer-numeric-literals': 'off',
      'prefer-object-has-own': 'off',
      'prefer-object-spread': 'off',
      'prefer-promise-reject-errors': 'off',
      'prefer-regex-literals': 'off',
      'prefer-rest-params': 'off',
      'prefer-spread': 'off',
      'prefer-template': 'off',
      radix: 'off',
      'require-await': 'off',
      'require-unicode-regexp': 'off',
      'sort-imports': 'off',
      'sort-keys': 'off',
      'sort-vars': 'off',
      strict: 'off',
      'symbol-description': 'off',
      'vars-on-top': 'off',
      yoda: 'off',
    },
  },
  // https://eslint.org/docs/latest/rules/#layout--formatting
  {
    rules: {
      'unicode-bom': 'off',
    },
  },
);

export function js({
  globals = true,
  ...config
}: Pick<ConfigWithExtends, 'extends' | 'rules'> & { globals?: boolean }) {
  return pluginTs.config(
    globals
      ? {
          languageOptions: {
            globals: {
              ...globalVariables.es2025,
            },
          },
        }
      : {},
    jsStrict,
    config,
  );
}
